- name: Configure all servers
  hosts: all
  become: true
  gather_facts: yes
  
  vars:
    ansible_user: "{{ 'rocky' if 'server_role_Database' in group_names else 'admin' }}"

  roles:
    - { role: redis, when: "'server_role_Database' in group_names" }
    - { role: frontend, when: "'server_role_Web' in group_names" }
